"""new mods

Revision ID: e19c1370ef8e
Revises: 
Create Date: 2022-09-12 21:01:51.405634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c1370ef8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Integer(), nullable=True),
    sa.Column('content1', sa.Integer(), nullable=True),
    sa.Column('content2', sa.Integer(), nullable=True),
    sa.Column('content3', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines')
    # ### end Alembic commands ###
